export const GET_PRODUCTS_STARTED = 'GET_PRODUCTS_STARTED'
export const GET_PRODUCTS_SUCCEEDED = 'GET_PRODUCTS_SUCCEEDED'
export const GET_PRODUCTS_FAILED = 'GET_PRODUCTS_FAILED'

export const POST_PRODUCT_STARTED = 'POST_PRODUCT_STARTED'
export const POST_PRODUCT_SUCCEEDED = 'POST_PRODUCT_SUCCEEDED'
export const POST_PRODUCT_FAILED = 'POST_PRODUCT_FAILED'

export const DELETE_PRODUCT_STARTED = 'DELETE_PRODUCT_STARTED'
export const DELETE_PRODUCT_SUCCEEDED = 'DELETE_PRODUCT_SUCCEEDED'
export const DELETE_PRODUCT_FAILED = 'DELETE_PRODUCT_FAILED'

export const PUT_PRODUCT_STARTED = 'PUT_PRODUCT_STARTED'
export const PUT_PRODUCT_SUCCEEDED = 'PUT_PRODUCT_SUCCEEDED'
export const PUT_PRODUCT_FAILED = 'PUT_PRODUCT_FAILED'

export const GET_PRODUCT_STARTED = 'GET_PRODUCT_STARTED'
export const GET_PRODUCT_SUCCEEDED = 'GET_PRODUCT_SUCCEEDED'
export const GET_PRODUCT_FAILED = 'GET_PRODUCT_FAILED'